import images from "../assets";

export const myProjects = [
	{
		tag: ["react JS", "all"],
		name: "HR System",
		description: "HR System Dashboard",
		url: "https://hrsystem-kuwait.vercel.app/login",
		img: images?.hr,
		code: "",
	},
	{
		tag: ["react JS", "all"],
		name: "Idea",
		description: "Learning Platform",
		url: "https://idea-kw.vercel.app/",
		img: images?.idea,
		code: "",
	},
	{
		tag: ["react JS", "all"],
		name: "Kanaloud Website",
		description: "E-commerce",
		url: "https://www.kanaloud.com/",
		img: images?.kanaloud,
		code: "",
	},
	{
		tag: ["react JS", "all"],
		name: "Kanaloud Dashboard",
		description: "Kanaloud Dashboard E-commerce",
		url: "https://admin.kanaloud.com/login",
		img: images?.kanaloudDashboard,
		code: "",
	},
	{
		tag: ["react JS", "all"],
		name: "Cloud Lift Solution",
		description: "Cloud Lift Solution + Dashboard",
		url: "https://cloud-lift-solution.vercel.app/",
		img: images.cloud,
		code: "",
	},
	{
		tag: ["angular", "all"],
		name: "Bazaar Ecommerce",
		description: "Bazaar Ecommerce website",
		url: "https://bazaar-ecommerce-sable.vercel.app/",
		img: images.bazaar,
		code: "https://github.com/muhammedosama8/bazaar-ecommerce",
	},
	{
		tag: ["angular", "all"],
		name: "muthmer",
		description: "muthmer website",
		url: "https://muthmer.vercel.app/",
		img: images.muthmer,
		code: "https://github.com/muhammedosama8/muthmer",
	},
	// {
	// 	tag: ["react JS", "all"],
	// 	name: "kabsah",
	// 	description: "resturant website",
	// 	url: "https://kabsah-store.vercel.app/",
	// 	img: images.kabsah,
	// 	code: "https://github.com/muhammedosama8/kabsah-store",
	// },
	// {
	// 	tag: ["web", "all"],
	// 	name: "dashboard",
	// 	description: "dashboard website",
	// 	url: "https://keen-dashboard.vercel.app/",
	// 	img: images.dashboard,
	// 	code: "https://github.com/muhammedosama8/keen-dashboard",
	// },
	{
		tag: ["task", "all"],
		name: "memory game",
		description: "memory game website",
		url: "https://memory-game-tau-henna.vercel.app/",
		img: images.memory,
		code: "https://github.com/muhammedosama8/memory-game",
	},
	{
		tag: ["react JS", "all"],
		name: "portfolio",
		description: "portfolio website",
		url: "https://muhammed-portfolio.vercel.app/",
		img: images.portfolio,
		code: "https://github.com/muhammedosama8/muhammed-portfolio",
	},
	// {
	// 	tag: ["web App", "all"],
	// 	name: "noon",
	// 	description: "ecommerce website",
	// 	url: "https://noon-website.vercel.app/",
	// 	img: images.noon,
	// 	code: "https://github.com/muhammedosama8/noon-website",
	// },
	{
		tag: ["task", "all"],
		name: "to do app",
		description: "tasks note",
		url: "https://to-do-tasks-app.vercel.app/",
		img: images.toDoTasks,
		code: "https://github.com/muhammedosama8/to-do-app",
	},
];
